# Generated by Django 4.2.6 on 2023-10-29 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meetups', '0002_alter_meetup_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meetup',
            name='slug',
            field=models.SlugField(blank=True, default='', unique=True),
        ),
    ]
