# Generated by Django 4.2.6 on 2023-10-29 12:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('meetups', '0004_meetup_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='meetup',
            name='image',
        ),
    ]
