# Generated by Django 4.2.6 on 2023-10-29 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meetups', '0005_remove_meetup_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='meetup',
            name='image',
            field=models.ImageField(default='', upload_to='images'),
        ),
    ]
