# Generated by Django 4.2.6 on 2023-10-29 19:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('meetups', '0007_location_alter_meetup_location'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='meetup',
            name='location',
        ),
        migrations.DeleteModel(
            name='Location',
        ),
    ]
