# Generated by Django 4.2.6 on 2023-10-30 12:07

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meetups', '0013_meetup_date_meetup_organizer_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meetup',
            name='date',
            field=models.DateField(default=datetime.datetime(2023, 10, 30, 12, 7, 0, 960616, tzinfo=datetime.timezone.utc)),
        ),
    ]
