# Generated by Django 4.2.6 on 2023-10-30 12:07

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meetups', '0014_alter_meetup_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meetup',
            name='date',
            field=models.DateField(default=datetime.datetime(2023, 10, 30, 12, 7, 16, 727381, tzinfo=datetime.timezone.utc)),
        ),
    ]
